import { Header } from '@/components/Header'
import type { Metadata } from 'next'
import { ThemeProvider } from '@/components/theme-provider'
import { QueryProvider } from './provider/useQueryProvider'
import NextAuthSessionProvider from './provider/sessionProvider'

import './global.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <NextAuthSessionProvider>
            <QueryProvider>
                <Header />
                {children}
            </QueryProvider>
          </NextAuthSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
